// src/lib/constants/routes.ts
export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  UPDATE_PASSWORD: '/update-password',
  AUTH_CALLBACK: '/auth/callback',
  ONBOARDING: '/onboarding',
  HOME: '/home',
  MARKETPLACE: '/marketplace',
  LISTINGS: '/listings',
  LISTINGS_NEW: '/listings/new',
  PURCHASE_REQUESTS: '/purchase-requests',
  PURCHASE_REQUESTS_NEW: '/purchase-requests/new',
  NOTIFICATIONS: '/notifications',
  MESSAGES: '/messages',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  SETTINGS: '/settings',
  SEARCH: '/search',
  MY_ACTIVITY: '/activity',
  LISTING_DETAILS: (id: string) => `/listings/${id}`,
  LISTING_EDIT: (id: string) => `/listings/${id}/edit`,
  POST_EDIT: (id: string) => `/posts/${id}/edit`,
};
